### ISSUE TITLE
data logger dynamic forward, backward and trackwidth not working

### ISSUE THREAD

**Issue by willsnow** [bb-frc-workshops/romi-examples#12]
I updated to latest version of this frc-characterization code and latest python app 2021.2.2, and I can't seem to get dynamic-forward, dynamic backward or trackwidth to move the robot at all.

Quasistatic forward/backward works just fine, but when I hit Dynamic Forward it drops the connection to network tables. 

Any thoughts on where I should look?

**Comment by phlogiston1** [comment]
I'm having the same problem - anybody have a fix?

**Comment by jpokornyiii** [comment]
Closing in favor of #25 as sysid has changed drastically over the years.
