### ISSUE TITLE
Readme is unclear in terms of characterization

### ISSUE THREAD

**Issue by mdurrani808** [bb-frc-workshops/romi-examples#14]
https://github.com/bb-frc-workshops/romi-examples/tree/main/romi-characterization#step-1

Here, it says to press F5 which is supposed to run simulation. However, the button binding varies from computer to computer. It is much more clear and less error prone to just say to run the robot code in simulation or similar verbage.

**Comment by jpokornyiii** [comment]
In light of changes in 2024, #25 will create a new example and deprecate characterization altogether.
