### ISSUE TITLE
Error in romi-characterization

### ISSUE THREAD

**Issue by PHK-007** [bb-frc-workshops/romi-examples#21]
After I cloned the repository, open romi-characterization in VS Code, update the gradle, and import the project into 2023 WPILib, there are 4 errors in Robot.java

![romi-characterization error](https://github.com/bb-frc-workshops/romi-examples/assets/64712559/35da936f-43b3-46ef-86cf-f378447d427f)

What should I do? Is there a library that I should have downloaded?

**Comment by PHK-007** [comment]
Never mind, I just have to download 2021.3.1 version of WPILib VS Code; the version I was using was too new and some imports are no longer used.

**Comment by jpokornyiii** [comment]
Yes, that is correct. We need to upgrade our repo to use the latest version and examples of wpilib. We intend to do that this off-season. I'm glad you got it to work!

**Comment by jpokornyiii** [comment]
FYI, there is this PR (unreviewed at this time, that may work for the reason wpilib version.

https://github.com/bb-frc-workshops/romi-examples/pull/20

**Comment by PHK-007** [comment]
I'll give that project a try. Meanwhile, after I got the project running, no window that looks like this 
![image](https://github.com/bb-frc-workshops/romi-examples/assets/64712559/084e58fb-29c7-4118-8f4a-11846020acaa)
popped up, just the regular robot simulation GUI. Are there any other additional steps that I should take?

**Comment by jpokornyiii** [comment]
It's been a while, but I believe this is a separate tool you will need to launch separately (https://github.com/wpilibsuite/frc-characterization). Once launched, you can start up your WPILIB VS Code for the Romi. If it is running you can Connect to Robot and follow the steps from there. HTH.

**Comment by PHK-007** [comment]
Sorry, I'm still kind of new at this but does that mean I should open 2 WPILib VS Code one for [romi-charactization](https://github.com/bb-frc-workshops/romi-examples/tree/main/romi-characterization) and one for [frc-characterization](https://github.com/wpilibsuite/frc-characterization)?

**Comment by jpokornyiii** [comment]
You should only have to open one (romi-characterization) and run the frc-characterization tool from the command line (Windows -> Command Prompt)

**Comment by PHK-007** [comment]
I see. Thank you so much for your help.
